[general]
live_config_reload = true

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 10, y = 10 }

[font]
size = 14
normal = { family = "CodeNewRoman Nerd Font Mono" }
# offset.y = -1
[colors]
primary.background = "#131313"
primary.foreground = "#ebdbb2"

selection.background = "#ebdbb2"
selection.text = "#655b53"

[colors.normal]
black   = "#272727"
red     = "#cc231c"
green   = "#989719"
yellow  = "#d79920"
blue    = "#448488"
magenta = "#b16185"
cyan    = "#689d69"
white   = "#a89983"

[colors.bright]
black   = "#928373"
red     = "#fb4833"
green   = "#b8ba25"
yellow  = "#fabc2e"
blue    = "#83a597"
magenta = "#d3859a"
cyan    = "#8ec07b"
white   = "#ebdbb2"
